version: '3.9'

services:
  db:
    image: postgres:15
    container_name: recon_db
    restart: always
    environment:
      POSTGRES_DB: recon_db
      POSTGRES_USER: recon_user
      POSTGRES_PASSWORD: recon_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  recon_engine:
    build: .
    container_name: recon_engine
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://recon_user:recon_pass@db:5432/recon_db
    ports:
      - "8000:8000"
    command: uvicorn recon_engine.api.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
